#!/usr/bin/env bash
# =============================================================================
# tools/publish-pages.sh — put the built product live on GitHub Pages
#
#   https://soheilxcoder.github.io/ecosystem-os/
#
# Pages is configured to serve the ROOT of the `deploy` branch. This script
# rebuilds site/ into dist/, proves it works, then publishes dist/ to that
# branch. Your working branch is never switched, never merged and never
# rewritten; the deploy branch is a generated artifact, so it is replaced
# wholesale on every run.
#
# Usage:
#   tools/publish-pages.sh              build, test, publish site, push source
#   tools/publish-pages.sh --site-only  publish the site, do not push source
#   tools/publish-pages.sh --dry-run    build and test only, push nothing
#
# Environment overrides:
#   PAGES_BRANCH=deploy   REMOTE=origin   SKIP_TESTS=1
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PAGES_BRANCH="${PAGES_BRANCH:-deploy}"
REMOTE="${REMOTE:-origin}"
SITE_ONLY=0
DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --site-only) SITE_ONLY=1 ;;
    --dry-run)   DRY_RUN=1 ;;
    -h|--help)   sed -n '2,26p' "$0"; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

step() { printf '\n\033[1m▸ %s\033[0m\n' "$1"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; }
die()  { printf '\n\033[31m✗ %s\033[0m\n\n' "$1" >&2; exit 1; }

command -v node >/dev/null || die "node is required"
command -v git  >/dev/null || die "git is required"

SRC_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
[ "$SRC_BRANCH" != "$PAGES_BRANCH" ] || die "refusing to run from the Pages branch itself ($PAGES_BRANCH)"

# ---------------------------------------------------------------- 1. verify --
step "Verifying the source against the design and i18n contracts"
node tools/build-site.mjs --check || die "verification failed — nothing was published"
ok "every route has a page module, every asset resolves, no CDN, no missing string"

# ------------------------------------------------------------------ 2. test --
if [ "${SKIP_TESTS:-0}" != "1" ]; then
  step "Rendering every screen for every role, in both languages"
  node tools/smoke-site.cjs || die "smoke test failed — nothing was published"
  ok "all screens render clean"
fi

# ----------------------------------------------------------------- 3. build --
step "Building dist/"
node tools/build-site.mjs || die "build failed"
[ -f dist/index.html ] || die "dist/index.html was not produced"
ok "dist/ is ready ($(du -sh dist | cut -f1))"

if [ "$DRY_RUN" = "1" ]; then
  step "Dry run — nothing pushed"
  ok "preview locally with:  node tools/serve-dist.cjs 4173"
  exit 0
fi

# ------------------------------------------------- 4. commit the source tree --
if [ "$SITE_ONLY" != "1" ]; then
  step "Committing the source on $SRC_BRANCH"
  git add -A
  if git diff --cached --quiet; then
    ok "nothing to commit"
  else
    git commit -q -m "site: rebuild the static product against the real data shapes

Replaces the V18 demo shell with a working single-page product:
13 routes, 11 role personas, full FA/EN, no CDN, no dependencies.
Verified by tools/build-site.mjs and tools/smoke-site.cjs."
    ok "committed $(git rev-parse --short HEAD)"
  fi
fi

# ---------------------------------------------------- 5. publish to Pages ----
step "Publishing dist/ to $REMOTE/$PAGES_BRANCH"

git remote get-url "$REMOTE" >/dev/null 2>&1 || die "no remote named '$REMOTE'"

TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

# A throwaway repository holding exactly the build output. This never touches
# your working tree, your index or your checked-out branch.
git init -q -b "$PAGES_BRANCH" "$TMP/pages"
cp -R dist/. "$TMP/pages/"
cd "$TMP/pages"
git add -A
git -c user.name="${GIT_AUTHOR_NAME:-$(git -C "$ROOT" config user.name || echo ecosystem-os)}" \
    -c user.email="${GIT_AUTHOR_EMAIL:-$(git -C "$ROOT" config user.email || echo pages@local)}" \
    commit -q -m "deploy: $(date -u +%Y-%m-%dT%H:%M:%SZ) from $(git -C "$ROOT" rev-parse --short HEAD)

Generated by tools/publish-pages.sh from site/. Do not edit by hand."
git remote add "$REMOTE" "$(git -C "$ROOT" remote get-url "$REMOTE")"

# The Pages branch is a build artifact: replacing it wholesale is correct and
# keeps its history short enough for Pages to rebuild quickly.
git push --force --quiet "$REMOTE" "$PAGES_BRANCH" || die "push to $PAGES_BRANCH failed — check your GitHub connection"
ok "pushed $(git rev-parse --short HEAD) to $PAGES_BRANCH"

# ------------------------------------------------------- 6. push the source --
if [ "$SITE_ONLY" != "1" ]; then
  step "Pushing $SRC_BRANCH"
  cd "$ROOT"
  if git push --quiet "$REMOTE" "$SRC_BRANCH"; then
    ok "source branch is up to date on GitHub"
  else
    printf '  \033[33m!\033[0m could not push %s — the site is still live, push it yourself later\n' "$SRC_BRANCH"
  fi
fi

# --------------------------------------------------------------- 7. report ---
URL="https://$(git -C "$ROOT" remote get-url "$REMOTE" \
  | sed -E 's#.*github\.com[:/]##; s#\.git$##' | tr '[:upper:]' '[:lower:]' | cut -d/ -f1) \
.github.io/$(git -C "$ROOT" remote get-url "$REMOTE" \
  | sed -E 's#.*github\.com[:/]##; s#\.git$##' | tr '[:upper:]' '[:lower:]' | cut -d/ -f2)/"

step "Done"
cat <<EOF
  Live at:   $URL
  Branch:    $PAGES_BRANCH (root)
  Source:    $SRC_BRANCH

  Pages takes 30-90 seconds to rebuild. Watch it with:
    gh api repos/:owner/:repo/pages --jq '.status'

  Preview the exact build locally without waiting:
    node tools/serve-dist.cjs 4173

  That server resolves /budget to budget.html and falls back to 404.html,
  which is how Pages behaves. python3 -m http.server does neither, so deep
  links look broken locally and work in production.
EOF
